""" QUE CORNNO ARMAMOS DE TODO ESTO

agenda

deficinicion de agenda

* contactos


* cargar datos (tirarlos en un archivo de texto)
apellido, nombre, email, telefono,dni

* PROCESO DE VERIFICACION a prueba de boludos
QUE PASA SI ES VACIO NO TOMO DATOS
QUE PASA SI INGRESA UN NUMERO TELEFONICO DE MAS DE 10 DIGITOS O CON ESPACIOS
QUE PASA SI INGRESA EN BLANCO UN CAMPO FUNDAMENTAL APELLIDO
O NOMBRE O DNI
QUE PASA SI ELMAIL NO TIENEN @

* PROCESO DE VERIFICACION a prueba de hijos de puta
* PROCESO DE NO DUPLICACION DE DATOS
    SI DATO DUPLICADO QUE HAGO? UNIFICO, ELIMINO
    REEMPLAZO SEGMENTO DEL DATO POR OTRO MAS NUEVO ACTUALIZO EL TELEFONO
    COMPLETO LO QUE FALTABA
    QUE PASA SI TIENE MAS DE UN TELEFONO
    QUE PASA SI TIENE MAS DE UN EMAIL
 
 
 funciones   
* almacenarlos (ALMACENAMIENTO CON FECHA Y HORA ASI PODEMOS VER DESDE CUANDO ES CONTACTO)
* actualizarlos
* buscarlos
    ULTIMOS CONTACTOS INGRESADOS
    POR FECHAS POR EJEMPLO EN EL ULTIMO MES. (NUEVOS CLIENTES)
    CONTACTOS CUYA CARACTERISTICA TELEFONICA SEA X
    CONTACTOS FEM MAS BIN TRIN ETC ETC
    CONTACTOS   POR APELLIDO 
                POR NOMBRE
    SEGMENTACION ETAREA POR EDADES O RANGOS ETAREOS
    y todos estos convinables tipo con checkbox
    y que por supuesto tire un listado tipo txt etc 

FRUTILLAS DEL POSTRE
 IMPORTACION Y EXPORTACION DE DATOS A OTRA AGENDA O TIPO DE AGENDAS
 ESTO ES PARA VOS TINCHO PANDASSSSSSSSS



"""
print("saludos maromans")